function createfigure(X1, YMatrix1, YMatrix2)
%CREATEFIGURE(X1,YMATRIX1,YMATRIX2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 28-Feb-2012 23:42:01

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(1,2,1,'Parent',figure1);
box(subplot1,'on');
hold(subplot1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',subplot1);
set(plot1(1),'Color',[0 0 1],'DisplayName','mktrf');
set(plot1(2),'Color',[1 0 0],'DisplayName','mktrf & hml');
set(plot1(3),'Color',[0 1 0],'DisplayName','mktrf & smb');

% Create title
title('Identity Matrix');

% Create xlabel
xlabel('gamma');

% Create ylabel
ylabel('gWg');

% Create subplot
subplot2 = subplot(1,2,2,'Parent',figure1);
box(subplot2,'on');
hold(subplot2,'all');

% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix2,'Parent',subplot2);
set(plot2(1),'Color',[0 0 1],'DisplayName','mktrf');
set(plot2(2),'Color',[1 0 0],'DisplayName','mktrf & hml');
set(plot2(3),'Color',[0 1 0],'DisplayName','mktrf & smb');

% Create title
title('Optimal Weighting Matrix');

% Create xlabel
xlabel('gamma');

% Create ylabel
ylabel('gWg');

% Create legend
legend(subplot2,'show');

% Create legend
legend(subplot1,'show');

